version: 1

formatters:
  standard:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard

  debug_handler:
    class: logging.FileHandler
    filename: debug.log
    formatter: standard

  test_handler:
    class: logging.FileHandler
    filename: tests.log
    formatter: standard

loggers:
  dify_llvm:
    level: DEBUG
    handlers: [console, debug_handler]
    propagate: false

  tests:
    level: DEBUG  
    handlers: [console, test_handler]
    propagate: false

  fastapi:
    level: INFO
    handlers: [console]
