version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard

  debug_handler:
    class: logging.FileHandler
    filename: logs/debug.log
    formatter: standard

  anyio_handler:
    class: logging.FileHandler
    filename: logs/debug_anyio.log
    formatter: standard

  test_handler:
    class: logging.FileHandler
    filename: logs/tests.log
    formatter: standard

  input_handler:
    class: logging.FileHandler
    filename: logs/req_input.log
    formatter: standard

loggers:
  rdify:
    level: DEBUG
    handlers: [console, debug_handler]
    propagate: false

  tests:
    level: DEBUG  
    handlers: [console, test_handler]
    propagate: false

  rdify.cancel_scope:
    level: DEBUG
    handlers: [anyio_handler]
    propagate: false

  rdify.req.input:
    level: DEBUG
    handlers: [input_handler]
    propagate: false